version: '3.8'

networks:
  curioscan-net:
    driver: bridge

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - curioscan-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - curioscan-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - redis
      - minio
    networks:
      - curioscan-net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app
      - ./models:/app/models
    depends_on:
      - redis
      - minio
    networks:
      - curioscan-net

  streamlit:
    build:
      context: ./streamlit_demo
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_demo:/app
    depends_on:
      - api
    networks:
      - curioscan-net
