{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "curioscan.fullname" . }}
  labels:
    {{- include "curioscan.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "curioscan.fullname" . }}-api
                port:
                  number: 8000
          - path: /streamlit
            pathType: Prefix
            backend:
              service:
                name: {{ include "curioscan.fullname" . }}-streamlit
                port:
                  number: 8501
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "curioscan.fullname" . }}-frontend
                port:
                  number: 3000
    {{- end }}
{{- end }}
