apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "curioscan.fullname" . }}-minio
  labels:
    {{- include "curioscan.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "curioscan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "curioscan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "minio/minio:latest"
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
