apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "curioscan.fullname" . }}-streamlit
  labels:
    {{- include "curioscan.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "curioscan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: streamlit
  template:
    metadata:
      labels:
        {{- include "curioscan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: streamlit
    spec:
      containers:
        - name: streamlit
          image: "{{ .Values.image.repository }}/streamlit:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8501
          resources:
            {{- toYaml .Values.streamlit.resources | nindent 12 }}